name: Deploy website
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - uses: actions/cache@v2
        with:
          path: ~/.cpan
          key: cpan-${{ runner.os }}-${{ hashFiles('**/cpanfile') }}
          restore-keys: |
            cpan-${{ runner.os }}-
            cpan-
      - run: cpan install chordpro
      - run: make && make songbook && make copypro && make archive
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir public \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}