name: Deploy website
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir src \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}