name: Deploy website
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - name: Cache CPAN Modules
        uses: actions/cache@v4
        with:
          path: local
          key: perl-${{ steps.perl.outputs.perl-hash }}
      - name: Install chordpro
        run: cpm install chordpro
      - name: Install exiftool
        run: apt install libimage-exiftool-perl -y
      - name: Make PDFs
        run: make && make songbook && make copypro && make archive
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --prod \
            --dir public \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}